[package]
name = "seriesdb"
version = "0.5.1"
authors = ["Chaoqian Xu <chaoranxu@gmail.com>"]
edition = "2021"

[dependencies]
rocksdb = "0.18.0"
bytes = "1.1.0"
byteorder = "1.4.3"
serde = "1.0.137"
rmp-serde = "1.1.0"
